### ISSUE TITLE
getUser returns a UserRecord, not a User

### ISSUE THREAD

**Issue by g-a-d** [launchdarkly/ld-openapi#79]
From some empirical testing against the live API it appears that the getUser operation ("GET /api/v2/users/project/environment/user_key") returns a UserRecord, not a User.

Can you confirm this is the desired behaviour? If so I'm happy to submit a PR to correct this.

Thanks.

**Comment by atrakh** [comment]
Hi @g-a-d,

Thanks for reporting this. Your suggestion is right, the correct response for this endpoint is a `UserRecord`.

I'll follow up again once these changes are released.

**Comment by atrakh** [comment]
Hey @g-a-d,

We just released a new version of the API spec and related clients. Can you try upgrading?

Closing the issue for now, but please feel free to reach out again if anything comes up :)

**Comment by g-a-d** [comment]
Hi @atrakh,
Thanks for making the change. I note you added the UserRecord tag to the getuser method, but the schema for the response is still User (spec/paths/users.yaml#52). This means that the APIs are still broken: please consider merging PR #81 .
Thanks!
